import { test, expect } from '@playwright/test';

test.describe('API Endpoints Suite', () => {

  test('GET /api/health returns 200 OK and healthy status', async ({ request }) => {
    const response = await request.get('/api/health');
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.status).toBe('ok');
    expect(body.service).toBe('Vriksh Vani API');
    expect(body).toHaveProperty('version');
    expect(body).toHaveProperty('timestamp');
  });

  test('GET /api/v1/species returns species catalog', async ({ request }) => {
    const response = await request.get('/api/v1/species');
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.success).toBe(true);
    expect(Array.isArray(body.data)).toBe(true);
    expect(body.data.length).toBeGreaterThan(0);
    expect(body.data[0]).toHaveProperty('name');
    expect(body.data[0]).toHaveProperty('idealVpdMin');
  });

  test('GET /api/v1/bio-readings with plantProfileId returns telemetry stream', async ({ request }) => {
    const response = await request.get('/api/v1/bio-readings?plantProfileId=plant_monstera01&limit=5');
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body.success).toBe(true);
    expect(Array.isArray(body.data)).toBe(true);
    expect(body.data.length).toBe(5);
    expect(body.data[0]).toHaveProperty('leafSurfaceTemp');
    expect(body.data[0]).toHaveProperty('computedVpd');
    expect(body.data[0]).toHaveProperty('emotionTag');
  });

  test('POST /api/v1/bio-readings ingests valid sensor payload', async ({ request }) => {
    const response = await request.post('/api/v1/bio-readings', {
      data: {
        plantProfileId: 'plant_e2e_test',
        leafSurfaceTemp: 24.5,
        ambientTemp: 25.0,
        relativeHumidity: 65,
        computedVpd: 1.05,
        vocGasResistance: 12500,
        healthScore: 95,
        emotionTag: 'Photosynthetic Joy 🌿',
      },
    });
    expect(response.status()).toBe(201);
    const body = await response.json();
    expect(body.success).toBe(true);
    expect(body.data.healthScore).toBe(95);
  });

  test('POST /api/v1/waitlist/join validates required email field', async ({ request }) => {
    const response = await request.post('/api/v1/waitlist/join', {
      data: { name: 'Test User' },
    });
    expect(response.status()).toBe(400);
    const body = await response.json();
    expect(body.success).toBe(false);
  });

  test('POST /api/v1/contact/submit submits support ticket', async ({ request }) => {
    const response = await request.post('/api/v1/contact/submit', {
      data: {
        name: 'Test E2E Runner',
        email: 'e2e-test@vrikshvani.com',
        subject: 'Automated E2E Verification',
        message: 'This is a synthetic test message generated by Playwright E2E suite.',
        reason: 'technical',
      },
    });
    expect(response.status()).toBe(201);
    const body = await response.json();
    expect(body.success).toBe(true);
  });

});
